### PR TITLE
example R: add the librpma example

### PR DESCRIPTION
**Pull request by ldorau**
In this example we want to introduce to you a basic way of accessing Persistent Memory when it is installed in a remote system. Remote Persistent Memory (or RPMem for short) is a way of doing this via a network by making use of the Remote Direct Memory Access (RDMA) technology.

This example is an introduction to RPMem. We will guide you briefly through setting up all required hardware and software components and verifying whether the connection works properly. Having that, we will show you how to access Persistent Memory on a remote system using the librpma library.

After completing this example you will know:
- what is RPMem and what it is good for,
- how RPMem is different comparing to PMem,
- what hardware and software components are required to start using RPMem,
- how to verify whether the RDMA network works properly,
- how to use librpma API to:
- establish a connection,
- prepare memory for remote manipulation,
- manipulate memory on the remote system,
- assure persistency of stores to the remote system.

Step-by-step you will:
- test the connection on the basic level using ping,
- test the connection RDMA capabilities using rping,
- review an application focusing on establishing a connection,
- review an application reading remote system's memory and writing it back in the persistent manner.

Co-authored-by: Oksana Salyk <oksana.salyk@intel.com>
Co-authored-by: Jan M Michalski <jan.m.michalski@intel.com>

Signed-off-by: Lukasz Dorau <lukasz.dorau@intel.com>

Ref: https://github.com/pmemhackathon/hackathon.web/pull/3

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon/1)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon/1)* status: 3 of 18 files reviewed, 2 unresolved discussions (waiting on @ldorau and @lukaszstolarczuk)

___
*[`examples/R/CMakeLists.txt` line 35 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon/1#-NBX5CmTC_UQ9qR94UC_:-NBX5CmTC_UQ9qR94UCa:b-dpx5dz) ([raw file](https://github.com/pmemhackathon/hackathon/blob/10fc2f00c748aeed095a8cd6daab861bf8b33ff1/examples/R/CMakeLists.txt#L35)):*
> ```CMake
> endmacro()
> 
> add_flag(-Wall)
> ```

do we really need to check if they are supported? if they are not we don't throw any CMake errors, so it won't matter;

This Cmake will be a bit simpler without this macro, I believe
___
*[`examples/R/common.h` line 8 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon/1#-NBX6AW4EE0l42pT-kex:-NBX6AW4EE0l42pT-key:b-n620lr) ([raw file](https://github.com/pmemhackathon/hackathon/blob/10fc2f00c748aeed095a8cd6daab861bf8b33ff1/examples/R/common.h#L8)):*
> ```objc
>  */
> 
> #ifndef COMMON_H
> ```

I believe you can add some prefix, like `PMEMHACKATHON_` to this header guard

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon/1)* status: 3 of 18 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[`examples/R/CMakeLists.txt` line 35 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon/1#-NBX5CmTC_UQ9qR94UC_:-NBXMaOl83cdTpMJzSxN:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon/blob/10fc2f00c748aeed095a8cd6daab861bf8b33ff1/examples/R/CMakeLists.txt#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we really need to check if they are supported? if they are not we don't throw any CMake errors, so it won't matter;

This Cmake will be a bit simpler without this macro, I believe
</blockquote></details>

Done.
___
*[`examples/R/common.h` line 8 at r1](https://reviewable.io/reviews/pmemhackathon/hackathon/1#-NBX6AW4EE0l42pT-kex:-NBXMxXhEwlsm9TD80Mf:b-896fix) ([raw file](https://github.com/pmemhackathon/hackathon/blob/10fc2f00c748aeed095a8cd6daab861bf8b33ff1/examples/R/common.h#L8)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe you can add some prefix, like `PMEMHACKATHON_` to this header guard
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
thx!

:+1: 

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon/1#-:-NBXUHM6A2Pf2ssRZMUU:bx9zns4)* status: 3 of 18 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by ldorau — COMMENTED** [review]
Thanks @lukaszstolarczuk  :-)

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon/1#-:-NBXXrdZ1JK4Zbq7Y2jP:b7nmv5y)* status: 3 of 18 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmemhackathon/hackathon/1#-:-NBYCcsr2KoRL-jMXZ6a:bnfp4nl)* status: 3 of 18 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
